src/blog/urls.py
from django.urls import path

from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView

app_name = 'blog'
urlpatterns = [
    path('', ArticleListView.as_view(), name='list'),
    path('<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('create', ArticleCreateView.as_view(), name='create'),
]

src/onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import home_view

app_name = 'products'
urlpatterns = [
    path('', home_view, name='home'),
    path('products/', include('products.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('snippets/', include('snippets.urls')),
    path('chat/', include('chat.urls')),
]

src/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h2>About us</h2>
{{ test }}
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base Title</title>
</head>
<body>
    {% include 'navbar.html' %}

    {% block content %} {% endblock %}
</body>
</html>

src/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/create.html
{% extends 'base.html' %}

{% block content %}
<form method="post"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

src/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<p>Detail Page</p>
{{ product.title }}
{% endblock %}

src/templates/home.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'products:create' %}">Add Product</a>
<ul>
    {% for item in products %}
    <li><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></li>
{% endfor %}
</ul>
{% endblock %}

src/templates/navbar.html
<nav>
    <ul>
        <li>Brand</li>
        <li>Contact</li>
        <li>About</li>
    </ul>
</nav>